# Generated by Django 2.1.5 on 2019-02-01 09:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='address',
        ),
    ]
