# Generated by Django 2.1.4 on 2019-01-20 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
