# Generated by Django 2.1.5 on 2019-02-01 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_menu_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='count',
            field=models.IntegerField(default=1),
        ),
    ]
