# Generated by Django 2.1.5 on 2019-02-01 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_menu_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='count',
        ),
    ]
