# Generated by Django 2.1.5 on 2019-01-10 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boarddb',
            name='bad_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boarddb',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='boarddb',
            name='good_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='boarddb',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
