# Generated by Django 2.1.5 on 2019-02-01 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_remove_menu_count'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='menu',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='store.Menu'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basket',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
