# Generated by Django 2.1.5 on 2019-02-01 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190201_0800'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
