# Generated by Django 2.1.5 on 2019-02-01 09:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_remove_account_address'),
        ('order', '0003_delete_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='basket',
            name='account',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='account.Account'),
            preserve_default=False,
        ),
    ]
